create table public.funciones (
  year smallint not null,
  nombre_funcion text not null,
  orden smallint generated by default as identity not null,
  lugar text not null,
  fecha_funcion text not null,
  hora_funcion text not null,
  constraint funciones_pkey primary key (year, nombre_funcion)
) TABLESPACE pg_default;

create table public.grupos (
  id text not null,
  nombre_corto text not null,
  year smallint not null,
  created_at timestamp with time zone not null default now(),
  orden smallint null,
  nombre_funcion text null,
  constraint grupos_pkey primary key (id),
  constraint grupos_nombre_funcion_year_fkey foreign KEY (nombre_funcion, year) references funciones (nombre_funcion, year) on update CASCADE on delete set null
) TABLESPACE pg_default;

create table public.alumnos (
  nombre text not null,
  grupo text not null,
  created_at timestamp with time zone not null default now(),
  id integer generated always as identity not null,
  year integer not null,
  constraint alumnos_pkey primary key (id),
  constraint alumnos_nombre_year_unique unique (nombre, year),
  constraint alumnos_grupo_fkey foreign KEY (grupo) references grupos (id) on update CASCADE on delete RESTRICT
) TABLESPACE pg_default;

create table public.entradas (
  id uuid not null default gen_random_uuid (),
  nombre_comprador text null,
  email_comprador text null,
  cantidad smallint not null default '1'::smallint,
  created_at timestamp with time zone not null default now(),
  id_alumno integer not null,
  cantidad_usada smallint not null default '0'::smallint,
  constraint entradas_pkey primary key (id),
  constraint entradas_id_alumno_fkey foreign KEY (id_alumno) references alumnos (id) on update CASCADE on delete RESTRICT,
  constraint cantidad_no_negativa check ((cantidad >= 0))
) TABLESPACE pg_default;

create table public.email_templates (
  key text not null,
  template text null,
  asunto text null,
  updated_at timestamp with time zone not null default now(),
  constraint email_templates_pkey primary key (key)
) TABLESPACE pg_default;

create table public.historial_cambios (
  id_historial integer generated always as identity primary key,
  tabla text not null,
  id_registro text,
  contexto_registro JSON,
  operacion VARCHAR(10) CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE')),
  campo text,
  valor_anterior text,
  valor_nuevo text,
  email_usuario text,
  created_at timestamp with time zone not null default now()
) TABLESPACE pg_default;

create index idx_historial_cambios_created_at on public.historial_cambios (created_at desc);
