name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  
  # Permitir ejecución manual desde la pestaña Actions
  workflow_dispatch:

# Configurar permisos para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un deployment concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: alta-app/package-lock.json
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: alta-app
      - name: Build
        run: npm run build
        working-directory: alta-app
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./alta-app/dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist