name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  
  # Permitir ejecución manual desde la pestaña Actions
  workflow_dispatch:

# Configurar permisos para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un deployment concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build Alta-App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: alta-app/package-lock.json
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
        with:
          working-directory: alta-app
      - name: Build
        run: npm run build
        working-directory: alta-app
        env:
          VITE_SUPABASE_URL: ${{ secrets.VITE_SUPABASE_URL }}
          VITE_SUPABASE_ANON_KEY: ${{ secrets.VITE_SUPABASE_ANON_KEY }}
      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v4
        with:
          name: alta-app-deploy
          path: ./alta-app/dist
          retention-days: 1

  deploy:
    name: Deploy Alta-App
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: alta-app-deploy
